### ISSUE TITLE
It seems only support HTTP but not TLS

### ISSUE THREAD

**Issue by lryong** [kaushalmodi/hugo-search-fuse-js#12]
My site uses TLS encryption, but after installing the plugin, I found that when triggering a search, only the URL starting with `http://XXX` is requested.

And this is my blog's website: https://blog.herbert.top

**Comment by kaushalmodi** [comment]
I have not seen that issue.. I have an https site as well: https://scripter.co/search/?q=emacs

Is it possible you have the http hard-coded somewhere in your theme?

**Edit**: I believe mine would be SSL encryption. Given that, I don't know how Fuse.js distinguishes between SSL and TLS.

**Comment by lryong** [comment]
@kaushalmodi  Since the site is now deployed on [netlify](https://www.netlify.com/), the theme used is this one: [hugo-theme-even](https://github.com/olOwOlo/hugo-theme-even). 

At the moment it seems that only this plugin is not working properly, I don't know if it is related to my configuration on netlify.

![image](https://user-images.githubusercontent.com/11936678/111095983-8727c680-8579-11eb-8979-57887c3bf5c3.png)

**Comment by lryong** [comment]
> I have not seen that issue.. I have an https site as well: https://scripter.co/search/?q=emacs
> 
> Is it possible you have the http hard-coded somewhere in your theme?
> 
> **Edit**: I believe mine would be SSL encryption. Given that, I don't know how Fuse.js distinguishes between SSL and TLS.

I found out that it was hard-coded in my site configuration, and now it's fixed, thanks!
