### ISSUE TITLE
Searching page is not safe

### ISSUE THREAD

**Issue by wangxinzhi0** [kaushalmodi/hugo-search-fuse-js#13]
Hello, 

I followed the steps to configure the relevant files, but the website is shown to be insecure and cannot be searched.
![image](https://user-images.githubusercontent.com/45959771/118283869-65f43f80-b502-11eb-9008-8a15b56faeb6.png)
 

I need to modify the web security settings to allow insecure content before I can search and display results
![image](https://user-images.githubusercontent.com/45959771/118283220-b3bc7800-b501-11eb-8b9f-5dae85f77721.png)

I have no idea to fix it, please do me a favor, thank you!

**Comment by kaushalmodi** [comment]
May be you are hosting your website on http and not https?

**Comment by kaushalmodi** [comment]
For example, on Firefox, when you visit that search page, you should see this padlock icon, and the URL should begin with "https://":

![image](https://user-images.githubusercontent.com/3578197/118285844-dddd4e00-b49f-11eb-8617-839e9ca50aef.png)
