### ISSUE TITLE
Where or how to unescape HTML codes in search results?

### ISSUE THREAD

**Issue by McFateM** [kaushalmodi/hugo-search-fuse-js#4]
This is awesome!  Just having one problem that I'm not sure how to resolve...

I have some search results returning:
```
Juan&rsquo;s blog post does a nice job of covering the steps necessary to engage Watchtower, GitHub, and an au…
```
Wondering where and how I can unescape my search results so that it displays as intended?  Like so:
```
Juan's blog post does a nice job of covering the steps necessary to engage Watchtower, GitHub, and an au…
```

**Comment by kaushalmodi** [comment]
I'm afraid I am unable to help you out with this. This project is simply creating a Hugo Component around the JavaScript code that other awesome developers have worked on. 

As I don't have JavaScript knowledge, I won't be able to help you if the issue you are seeing has to so with the JS code. 

In any case, I'd suggest that you point me to a minimal example site repo that reproduces this issue. That way, me or someone else can debug and attempt to fix it.

**Comment by kaushalmodi** [comment]
I have a guess what might be causing this issue. I'll have a look today if I get a chance.

**Comment by McFateM** [comment]
Thanks!   I have a similar situation… not a Javascript expert.  I did fumble in the JS code a bit yesterday and thought I’d found a solution using calls to the JS unescape() function inside search.js and the ‘populateResults()’ function, but it didn’t work properly.   If I find a fix that works I’ll be sure to let you know.

On May 24, 2019, at 6:49 AM, Kaushal Modi <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a guess what might be causing this issue. I'll have a look today if I get a chance.

**Comment by SummittDweller** [comment]
I've confirmed that I can replace the "snippet" text by replacing line 73 in search.js.  That line reads...
```
frag.querySelector(".search_snippet").textContent = snippet;
```
Unfortunately, I'm not sure how to replace that string?  But changing it to this does not work:
```
frag.querySelector(".search_snippet").textContent = unescape(snippet);
```

**Comment by SummittDweller** [comment]
I figured this out.  WIll post the solution here when I return (in an hour).

**Comment by SummittDweller** [comment]
Turns out Javascript's _unescape()_ function is deprecated, and more importantly, it's ancient and only covers a small subset of all HTML codes.  The codes in my text were generally not covered, and its replacement function, decodeURI(), apparently isn't a good fit either.

I found the fix that I applied as indicated in the comment below.  The new code snippet in _search.js_ and the _populateResults()_ function is:

```
...
    snippet += "…";

    // Lifted from https://stackoverflow.com/posts/3700369/revisions
    var elem = document.createElement('textarea');
    elem.innerHTML = snippet;
    var decoded = elem.value;

    // Pull template from hugo template definition
    let frag = document.getElementById('search-result-template').content.cloneNode(true);
...
```
