### ISSUE TITLE
GNU LibreJS blocks the JavaScript

### ISSUE THREAD

**Issue by Robin-Wils** [kaushalmodi/hugo-search-fuse-js#6]
The GNU LibreJS extension blocks the JavaScript.
https://www.gnu.org/software/librejs/free-your-javascript.html

I just discovered this and wanted to inform this project about it. I am happy with this project and don't know how hard it is to fix this. It is pretty simple to fix it for inline JS, but JS libraries might be harder.

Honestly, this is why LibreJS just can't succeed in my opinion. It should be easier or it should be a standard, but hey, every extra visitor is an extra visitor.

**Comment by kaushalmodi** [comment]
Hello, thanks for letting me know. As I have mentioned in the credits of this project, I am not a web developer, and have zero JS knowledge. 

I simply made a Hugo "plugin" on top of the JS work done by someone else. 

I am definitely open to a PR that makes this compatible with LibreJS (honestly, I don't even know what that means :)). 

Is that plugin blocking the thin JS wrapper in this Hugo theme component? Or is it blocking the whole Fuse.js framework?

If it's the latter, then posting in the Fuse.js might help. 

In any case, if you post the error messages or anything that can help debug this in this thread, then may be a JS knowledgeable person can help out.

**Comment by Robin-Wils** [comment]
GNU LibreJS is from the Free Software Foundation. It only allows the execution of free JavaScript. It does so by following its rules. Those rules are not a standard as far I know, so most sites are not compatible with GNU LibreJS.

The link which you can find in my first comment contains info about the rules which GNU LibreJS expects. I am not sure how many people care about this, but it is at least known now.

**Comment by Robin-Wils** [comment]
I have played with GNU LibreJS before. I might look into a pull-request. It should be doable. I personally don't really care much about GNU LibreJS anymore, but others do.

**Comment by Robin-Wils** [comment]
For other people who want to look into this. 
A bit of GNU LibreJS compatibility was implemented: https://github.com/kaushalmodi/hugo-search-fuse-js/pull/7

**Comment by kaushalmodi** [comment]
I'll just close this as there's nothing I can do to fix it.

**Comment by Robin-Wils** [comment]
It is kind of a stupid idea anyways. LibreJS takes a weird approach, and is hard to support.
