### ISSUE TITLE
Redirecting somehow fails?

### ISSUE THREAD

**Issue by Robin-Wils** [kaushalmodi/hugo-search-fuse-js#8]
I am starting to migrate my site to codeberg. 
My search suddenly no longer works.

https://pages.codeberg.org/RobinWils/search/index.html

**Comment by Robin-Wils** [comment]
I think that it is caused because codeberg automatically adds `/index.html` to the URL. 

So the JavaScript should check if `/index.html` is in the last part of the URL and replace it with `/` if it does exist. That shouldn't be too hard to implement. I might look into it when I find some time.

**Comment by Robin-Wils** [comment]
I personally no longer need this fix, but it might be useful for some other people. Some webservers automatically redirect to `search/index.html` instead of `search/`. 

I suggested this extra redirect feature to codeberg, and they fixed it during the same day. I am impressed by how fast they fix stuff. It is amazing!

**Comment by kaushalmodi** [comment]
Hello,

I don't entirely understand where exactly that search/replace should go. I have only "assembled" this Hugo theme component. Credit for the existence of `search.js` goes to all its contributors (I have zero JS knowledge _.. I think I have mentioned that to you in an earlier PR :)_). If you have a PR that fixes this, I will be happen to test and merge it.

**Comment by Robin-Wils** [comment]
To be honest. I think that no one else will encounter this bug. Most webservers allow `search/` URLs. `search/` automatically became `search/index.html` at first, before I asked codeberg to add that feature. 

This bug does only exist on webservers which automatically send you to `/index.html` pages. I am not sure what the JavaScript regex exactly does. I would have created a pull-request if I had found a fix. I could have done some tests, but I am not sure of it is worth the effort.

The bug was more of a webserver issue than a JavaScript issue I believe.

**Comment by Robin-Wils** [comment]
I suggest to close this issue, someone will reopen an issue if it really is a problem, but I think that not many other people would encounter this bug.
