### ISSUE TITLE
Search result is highlighted only if it's in the beginning of a post

### ISSUE THREAD

**Issue by iootaa** [kaushalmodi/hugo-search-fuse-js#9]
Hi there,

this was successfully tested with the theme BeautifulHugo. Thank you!

This is a minor issue, but the search term is successfully highlighted only if it's in the beginning of a post. In case the term is beyond, it would be great to have a quote of the relevant part (where the searched term appears)

**Comment by Robin-Wils** [comment]
I am a bit late with commenting on this, but it should be resolved.

**Comment by kaushalmodi** [comment]
Thanks @Robin-Wils, I'll close this as this is fixed. Sample screenshot:

![Screenshot_20220129-092241](https://user-images.githubusercontent.com/3578197/151664541-1031a754-683a-4829-8196-9f9461fe3a09.png)
